export const serbian_cities = [
    'Beograd', 'Novi Sad', 'Niš', 'Kragujevac', 'Subotica',
    'Zrenjanin', 'Pančevo', 'Čačak', 'Novi Pazar', 'Kraljevo',
    'Smederevo', 'Leskovac', 'Valjevo', 'Kruševac', 'Vranje',
    'Šabac', 'Užice', 'Sombor', 'Požarevac', 'Pirot',
    'Zaječar', 'Kikinda', 'Sremska Mitrovica', 'Jagodina', 'Vršac',
    'Bor', 'Prokuplje', 'Loznica', 'Ada', 'Aleksandrovac',
    'Aleksinac', 'Alibunar', 'Apatin', 'Aranđelovac', 'Arilje',
    'Babušnica', 'Bajina Bašta', 'Batočina', 'Bač', 'Bačka Palanka',
    'Bačka Topola', 'Bački Petrovac', 'Bela Crkva', 'Bela Palanka', 'Beočin',
    'Bečej', 'Blace', 'Bogatić', 'Bojnik', 'Boljevac',
    'Bosilegrad', 'Brus', 'Bujanovac', 'Crna Trava', 'Despotovac',
    'Dimitrovgrad', 'Doljevac', 'Gadžin Han', 'Golubac', 'Gornji Milanovac',
    'Inđija', 'Irig', 'Ivanjica', 'Kanjiža', 'Kladovo',
    'Knić', 'Koceljeva', 'Kosjerić', 'Kovačica', 'Kovin',
    'Kuršumlija', 'Lajkovac', 'Lapovo', 'Lebane', 'Ljig',
    'Ljubovija', 'Lucani', 'Majdanpek', 'Mali Iđoš', 'Malo Crniće',
    'Medveđa', 'Merošina', 'Mionica', 'Nova Varoš', 'Nova Crnja',
    'Novi Bečej', 'Novi Kneževac', 'Odžaci', 'Opovo', 'Osečina',
    'Pećinci', 'Petrovac na Mlavi', 'Plandište', 'Preševo', 'Rača',
    'Raška', 'Rekovac', 'Ruma', 'Sečanj', 'Senta',
    'Sevojno', 'Smederevska Palanka', 'Sokobanja', 'Srbolovo', 'Srbobran',
    'Sremski Karlovci', 'Stara Pazova', 'Surdulica', 'Svilajnac', 'Svrljig',
    'Temerin', 'Titel', 'Topola', 'Trgovište', 'Trstenik',
    'Tutin', 'Ćićevac', 'Ćuprija', 'Ub', 'Ulovac',
    'Varvarin', 'Velika Plana', 'Veliko Gradište', 'Vitina', 'Vladimirci',
    'Vladičin Han', 'Vladimirovac', 'Vrbas', 'Vrnjačka Banja', 'Žabalj',
    'Žagubica', 'Žitište', 'Žitorađa'
  ];